#-setting the port
server:
  port: 8082

#-setting the application name
spring:
  application:
    name: LOGIN-SERVICE
  data:
    mongodb:
         uri: mongodb+srv://admin:admin@flightbookingwebapp.n5q6g.mongodb.net/FlightBookingWebApp?retryWrites=true&w=majority

#-for registering with Eureka Server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
