server:
    port: 8082
spring:
    application:
        name: fare-management
    data:
        mongodb:
            uri: mongodb+srv://admin:admin@flightbookingwebapp.n5q6g.mongodb.net/FlightBookingWebApp?retryWrites=true&w=majority