server:
   port: 8085
spring:
   application:
      name: booking-management
   data:
      mongodb:
         uri: mongodb+srv://admin:admin@flightbookingwebapp.n5q6g.mongodb.net/FlightBookingWebApp?retryWrites=true&w=majority
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/flightauth
      username: root
      password: password
   jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
